---
kind: pipeline
type: docker
name: xenial-amd64

platform:
  arch: amd64

steps:
  - name: base
    image: plugins/docker
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 18.04-base
        - 18.04-base-amd64
      dockerfile: ubuntu/18.04/Dockerfile.base
  - name: build
    image: plugins/docker
    depends_on:
      - base
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 18.04-build
        - 18.04-build-amd64
      dockerfile: ubuntu/18.04/Dockerfile.build

---
kind: pipeline
type: docker
name: focal-amd64

platform:
  arch: amd64

steps:
  - name: base
    image: plugins/docker
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 20.04-base
        - 20.04-base-amd64
      dockerfile: ubuntu/20.04/Dockerfile.base
  - name: build
    image: plugins/docker
    depends_on:
      - base
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 20.04-build
        - 20.04-build-amd64
      dockerfile: ubuntu/20.04/Dockerfile.build

---
kind: pipeline
type: docker
name: focal-arm64

platform:
  arch: arm64

steps:
  - name: base
    image: plugins/docker
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 20.04-base
        - 20.04-base-arm64
      dockerfile: ubuntu/20.04/Dockerfile.base
  - name: build
    depends_on:
      - base
    image: plugins/docker
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      compress: true
      repo: charlesportwoodii/ubuntu
      tags:
        - 20.04-build
        - 20.04-build-arm64
      dockerfile: ubuntu/20.04/Dockerfile.build


---
kind: pipeline
type: docker
name: focal-manifest

platform:
  arch: amd64

depends_on:
  - focal-amd64
  - focal-arm64

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      config:
        from_secret: DOCKER_AUTH_CONFIG
      target: 20.04-build
      template: charlesportwoodii/ubuntu:20.04-build-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
