---
kind: pipeline
type: docker
name: xenial-amd64

platform:
  arch: amd64

steps:
  - name: base
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags:
        - charlesportwoodii/ubuntu:18.04-base
        - charlesportwoodii/ubuntu:18.04-base-amd64
      dockerfile: ubuntu/18.04/Dockerfile.base
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags:
        - charlesportwoodii/ubuntu:18.04-build
        - charlesportwoodii/ubuntu:18.04-build-amd64
      dockerfile: ubuntu/18.04/Dockerfile.build