---
kind: pipeline
type: docker
name: alpine-3.14-buildx

platform:
  arch: amd64

steps:
  - name: alpine-3.14-base-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f alpine/3.14/Dockerfile.base --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/alpine:3.14-base --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine-3.14-build-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f alpine/3.14/Dockerfile.build --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/alpine:3.14-build --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: alpine-3.15-buildx

platform:
  arch: amd64

steps:
  - name: alpine-3.15-base-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f alpine/3.15/Dockerfile.base --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/alpine:3.15-base --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine-3.15-build-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f alpine/3.15/Dockerfile.build --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/alpine:3.15-build --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: jammy-buildx

platform:
  arch: amd64

steps:
  - name: jammy-base-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f ubuntu/22.04/Dockerfile.base --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/ubuntu:22.04-base --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: jammy-build-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f ubuntu/22.04/Dockerfile.build --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/ubuntu:22.04-build --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: focal-buildx

platform:
  arch: amd64

steps:
  - name: focal-base-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f ubuntu/20.04/Dockerfile.base --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/ubuntu:20.04-base --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: focal-build-buildx
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - apk add --no-cache curl
      - mkdir -p ~/.docker/cli-plugins
      - curl -Lqqs https://github.com/docker/buildx/releases/download/v0.8.2/buildx-v0.8.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx create --use
      - docker login -u=$username -p=$password
      - docker buildx build -f ubuntu/20.04/Dockerfile.build --push --platform linux/arm64,linux/amd64 -t charlesportwoodii/ubuntu:20.04-build --no-cache --compress .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock