---
kind: pipeline
type: docker
name: xenial-amd64

platform:
  arch: amd64

steps:
  - name: xenial-base
    image: docker
      - docker build -f ubuntu/18.04/Dockerfile.base -t charlesportwoodii/ubuntu:18.04-base-amd64 -t charlesportwoodii/ubuntu:18.04-base --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: xenial-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:18.04-base-amd64
  - name: xenial-build
    image: docker
      - docker build -f ubuntu/18.04/Dockerfile.build -t charlesportwoodii/ubuntu:18.04-build-amd64 -t charlesportwoodii/ubuntu:18.04-build --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: xenial-build-push
    depends_on:
      - xenial-base
      - xenial-build
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:18.04-build-amd64

---
kind: pipeline
type: docker
name: focal-amd64

platform:
  arch: amd64

steps:
  - name: focal-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/ubuntu:20.04-base-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: focal-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:20.04-base-amd64
  - name: focal-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/ubuntu:20.04-build-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: focal-build-push
    image: docker
    depends_on:
      - focal-base
      - focal-build
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:20.04-build-amd64

---
kind: pipeline
type: docker
name: focal-arm64

platform:
  arch: arm64

steps:
  - name: focal-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/ubuntu:20.04-base-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: focal-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:20.04-base-arm64
  - name: focal-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/ubuntu:20.04-build-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: focal-build-push
    depends_on:
      - focal-base
      - focal-build
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/ubuntu:20.04-build-arm64

---
kind: pipeline
type: docker
name: focal-amd64

platform:
  arch: amd64

depends_on:
  - focal-amd64
  - focal-arm64

steps:
  - name: focal-manifest-create
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker manifest create charlesportwoodii/ubuntu:20.04-build --amend charlesportwoodii/ubuntu:20.04-build-amd64 --amend charlesportwoodii/ubuntu:20.04-build-arm64
      - docker manifest push charlesportwoodii/ubuntu:20.04-build

---
kind: pipeline
type: docker
name: alpine3.11-amd64

platform:
  arch: amd64

steps:
  - name: alpine3.11-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/alpine:3.11-base-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.11-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.11-base-amd64
  - name: alpine3.11-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/alpine:3.11-build-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.11-build-push
    image: docker
    depends_on:
      - alpine3.11-base
      - alpine3.11-build
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.11-build-amd64

---
kind: pipeline
type: docker
name: alpine3.11-arm64

platform:
  arch: arm64

steps:
  - name: alpine3.11-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/alpine:3.11-base-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.11-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.11-base-arm64
  - name: alpine3.11-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/alpine:3.11-build-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.11-build-push
    depends_on:
      - alpine3.11-base
      - alpine3.11-build
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.11-build-arm64

---
kind: pipeline
type: docker
name: alpine3.11-amd64

platform:
  arch: amd64

depends_on:
  - alpine3.11-amd64
  - alpine3.11-arm64

steps:
  - name: alpine3.11-manifest-create
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker manifest create charlesportwoodii/alpine:3.11-build --amend charlesportwoodii/alpine:3.11-build-amd64 --amend charlesportwoodii/alpine:3.11-build-arm64
      - docker manifest push charlesportwoodii/alpine:3.11-build

---
kind: pipeline
type: docker
name: alpine3.14-amd64

platform:
  arch: amd64

steps:
  - name: alpine3.14-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/alpine:3.14-base-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.14-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.14-base-amd64
  - name: alpine3.14-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/alpine:3.14-build-amd64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.14-build-push
    image: docker
    depends_on:
      - alpine3.14-base
      - alpine3.14-build
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.14-build-amd64

---
kind: pipeline
type: docker
name: alpine3.14-arm64

platform:
  arch: arm64

steps:
  - name: alpine3.14-base
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.base -t charlesportwoodii/alpine:3.14-base-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.14-base-push
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.14-base-arm64
  - name: alpine3.14-build
    image: docker
      - docker build -f ubuntu/20.04/Dockerfile.build -t charlesportwoodii/alpine:3.14-build-arm64 --compress --no-cache .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: alpine3.14-build-push
    depends_on:
      - alpine3.14-base
      - alpine3.14-build
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker push charlesportwoodii/alpine:3.14-build-arm64

---
kind: pipeline
type: docker
name: alpine3.14-amd64

platform:
  arch: amd64

depends_on:
  - alpine3.14-amd64
  - alpine3.14-arm64

steps:
  - name: alpine3.14-manifest-create
    image: docker
    environment:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u=$username -p=$password
      - docker manifest create charlesportwoodii/alpine:3.14-build --amend charlesportwoodii/alpine:3.14-build-amd64 --amend charlesportwoodii/alpine:3.14-build-arm64
      - docker manifest push charlesportwoodii/alpine:3.14-build

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
