sudo: required

language: generic

services:
  - docker

env:
  matrix:
    - IMAGE=trusty
    - IMAGE=xenial
    - IMAGE=centos7
    - IMAGE=rhel7

  global:
  # Docker Email
  - secure: hTz5hqFgOwlUy8TrvxNjZQThhdj0D5AVBWLCE6NjvMx6fNEVgOqt0Pfsaa4z/t0sqst83+yJLvFGZZiVA5xA5WB4mLvR7oZ/DXOyj602/aiim9hLlLX8NMLbXUSVyMuY5IPwQFGgJqf4eUVScMfJqKy2WRCTqg8Rv6BvXkQwMU+zUN76zMlKY1wWbBE2uGUeyCwdyrTFzsUggxiR6mzQtROMx+ryAcwnktg6Fg1N5xQJkuhp208+dyHpey7eVZnio07snCPuOXHmR9micia+oW77pHx4V0P77tpC3nzfBwvVHthSNt4STGlS+Q+kBQtf9Fc8F0YWV6bgV5LItO4X35b3u2Z4g1Z7t7371/JSo6p96zHtaLvxGx7u5UoPdH7am/+kTJcfLVHpyJsN7wt2NAgmFL5Qn+6OQngm8g2pAbWyLHkSKjcsBGGDr6Oa3F+RmDblsNv1Ls1r6Z1E25dg5wtna0dtWrrM5PLnZ76M+gb3h17ObwoXhdBjXKk2CxkDZtMWd46pO5vgq7wWY8RPq9mvISJNKh2U94smfo3Kj/Ow5dpNMqAXJAnMIqXtTe/yntc/cPvEhrZFB1pnolSsa1/6aOKqFGPYzm13y63UFSOLY/GtxJbjaEpnybo+8tWAN1B5s88Wot8AOT2izSNK5alKl/FAP/M8XQkt9f2bbo8=
  # Docker Username
  - secure: eEsFsnGv15GJWs05bh0db+RoBL8q79bsuJpke5Z0lGk69m8Pa/zpLHFO4V+wvZq05plHiL2w43cnTgFNEjEuN2LVhgwO6WDC/RCv1b3ayRkbEkz1yBsme1yafrjmNXrcMNvKu0YbOU8efVP76AxJKLjlfnwxfzZVbvhTGmroiDHDlVLLsE1H/QJ9pEnlc4vzxy6VIpdB+YZ3v2bFQOTKWzgxzmubSijA2OOAasotU9MHn8TUi96QHUuYTqv/4J3S4HRpAoKcYBS4cF5Q1Aqmz62yLf7MQoKkYfdbZ4tuEc/Ft5Bx4WXK4TklPuYwB53JRwBWdInH+yJp4RlHWA4792vTr9YgveZPiVo0SNMRoaDhgAw+7VIPJ6+74r2QLNqlk40+/t5w1FIFS1Nln1EomG/jUQpF07aQVvRQr5q/jWeBDinf0oPLj0nzLTe0B7KGdjGhMFBR4vNkkHFfB4ylMEprARDhY6JJSAF/LqMGYXBklGD+lcvumOGATe64hYl47iwDC6oD3sCS2f/qBxj1c0QSmNgSjGeOPv+wyeH4zoKbKkQYbCs6rYYE+m+oYtDO8KAAIukoYyX5Ewi9H4Dk31bViHM3Yhn/MJFzrAjS1hsVUsV+3pi0hzE9ArRk5HAECma5suxd+7hS252mxZiCCxQakSmicx6RxjS0dCz1/vY=
  # Docker Pass
  - secure: "hFvkk0Oo3jN4Ijj/qiS3mcTVNOj6msMQqtsQnhekjtEGY4DGfmz3no23Zr/GAXr8MOZCpk6bj0R8JcdLJJTsUziyyujtchm7knm1B5naevaX82UG/DVGkH0lKwYOkM3ff+FOL5FnNV2+onf1OUQvARSaneGTmlTtoHBrejYIVlfyY8Mvd60AJNW6UWOEKxCP8Xz8XUs50fVElWIvYslDTJI6r/9n83jXM5Eva6/gOlW7LZjvCXTORQeOXv8VL8ppuBljxsLQ5dRSJw/8EhNDwcftAknFE+7dS7W3qPoto416mY0iPO/ZxacXTDJgaYAjI+pA2W5V0JPH/oQGR6hWh+Miw4zSrMOEdeBIREei9shVsytigVDxHh2wBdO/TozI+AUBxNhUOEZhV8aTbloxpQ9qPbySuaNY29ynOyi30saz94sWz/5+tSLvt7aAHKLgNU+12PD2ZnLyD5XWfM8KtN26upSFkq2xQLMyy1KKAEdjk951DkO5WMJiJHTTcEpN+Reqy4a2V8jIFxkaEs6yashNGbRciYaMjTW5xC7n74rbE93/Q9zxvgiwZEAu+T6p3NWKyg0//RmlEjTN9pwsufFhfG1+0Tblo/1wjlv++51RktPtk8SQTce1lcSwWW28Ar5mnUSm4HlHMprEPZP8mY+mKx2stN6q6i/+W0b1o6A="
  # RedHat Username
  - secure: "SeRMLcyavpyyTSE1qvEWXpLyqKH9sMEM9Hk+j0vIpAJLaoIXm1lCyBaWdGTUpeFyc4U6aNq6UuIwD+CRXmg08AxFD+3LwxxnWkQsIzNHsVijpCRGet0ALa/dvagZfzzoo8GxBFwMIMAE4n60ziLbp636iac1dCW11GYPpw4gCdRKCdNESwUtmhmHn/pLHi2EFTZcuNDD4jI3A5niEf6vjFKuY/it75/tSeTsqxTgk/TFAsYgi41suGE27bRz82PtsdcdLGkl1n0rDVN8jFUK7ygCnpsX4/U2soWgaJjitxrSF8YqnpukG+QMWYznDrqlQeJEAN1H4H/FundZo5oNaKRkpe/M87IzseeTyS3NHBYaEGAbcs5lEFS5OsjVh3alIIg1nj9JvrLTRpZq0Axq+PzBjcFfDtJWv6iEmDZnoGa1I0T6zPp4pCBHHyKpcnZ1NqAMhGQ7ObSaqhdJ+R2bZCvCJcq2tFCaVXPzFa3a0L3wCaINWE2ZDxU8nUJG07/l0arwjpeXl1qk8ZNax06w00qsMVE2ndm/cjMOMdNQl/cEWIsWQn/4ds6PnHFGn2wvxZTXIj+OgKz8wBIsWqvZ0tlOXezf2tmPuKE2/nw3scNXzhnyas0MAhTtPojSsZExkyGF3m7RQsfl0N/ESgTRPIJArIMeerJS6F5SA2hExYs="
  # RedHat Pass
  - secure: "t9r938YZi/q5NmLfrU2SyVIeqYvjngHNwS4cIAS0Shnl/sYZERwh7iuivGACL/yLBl0nGOT+CChhewwl6fZIZ6jn0rHuCDhd0mTIEydXP2c4jTrEKkPpB3GT67sZzn7dbADHRMYFHhzaC3sieaFaxEcXA0kS6Ao5PQSgJH/GdJ6ZmeMEKvpSETtSGMTMnkemJvWor4If8NYF7dTPNZFwZaHBcSSzCGdvAmSD1Tvga86xJAuI9pUGSuszM2kCX9Rqxzf1uaiq0p+DwJsumCp57sHCItqQc0NmTIjb2uZ1vzQ1a9vW2gubZZrsYi5niRajfPyv8hC/MjZ/gvPAuHeR3NNostXa9UP+SHKlMqqQIHJODh3OkkbwxkVVYaUZudvOOUlLES405JhZjZl7+/RU6nrBdcr8SloeiGoyoWZoONC5kIEufBi3A/smgIivtquO80uMdxEiOTf2jwF9CeQrRFrT1kKsS4nNcqLLBuFdFj2SUkod8ZQSD6FdyGpZhm5nYAK13U5VnEgivG9Xj+GLE62Zi6wKyC7dThEDucauR4vwtOqgiAA1yWoJeVlrjz1e+JP8upQsNkkygBQyKt33TeKaW91PZwWOIvsUHHSYmC7sLxaxWqIsW3Ef4cRgJMDQb2TrACTdQt6Dw9Z8QnSlAfhMMa8b/sk8wiHbqagglqE="
  - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - export REPO=charlesportwoodii/docker-images
  - export TAG=$IMAGE

script:
  - docker build -f $IMAGE/Dockerfile -t $REPO:$COMMIT . --build-arg REDHAT_USER=$REDHAT_USER --build-arg REDHAT_PASS=$REDHAT_PASS
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
