dist: trusty
sudo: required
language: generic

matrix:
  fast_finish: true

env:
  matrix:
    - OS=ubuntu IMAGE=base RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=18.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=18.04
    - OS=centos IMAGE=base RELEASE_VERSION=7
    - OS=centos IMAGE=build RELEASE_VERSION=7
    - OS=rhel IMAGE=base RELEASE_VERSION=7
    - OS=rhel IMAGE=build RELEASE_VERSION=7
    - OS=alpine IMAGE=base RELEASE_VERSION=3.6
    - OS=alpine IMAGE=build RELEASE_VERSION=3.6
    - OS=alpine IMAGE=base RELEASE_VERSION=3.7
    - OS=alpine IMAGE=build RELEASE_VERSION=3.7
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce -y -qq
  - echo "DOCKER_OPTS=--experimental=true " | sudo tee --append /etc/default/docker
  - sudo service docker restart

before_script:
  - docker version
  - export IMAGE_NAME="charlesportwoodii/$OS:$RELEASE_VERSION-$IMAGE"
  - echo $IMAGE_NAME
  - echo $DOCKER_USER
  - echo "export REDHAT_USER=$REDHAT_USER" > .secrets
  - echo "export REDHAT_PASS=$REDHAT_PASS" >> .secrets
 
after_script:
  - rm .secrets

script:
  - docker build -f $OS/$RELEASE_VERSION/Dockerfile.$IMAGE -t $IMAGE_NAME --compress --squash .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $IMAGE_NAME
