dist: trusty
sudo: required
language: generic

matrix:
  fast_finish: true

env:
  matrix:
    - OS=ubuntu IMAGE=base RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=18.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=18.04
    - OS=centos IMAGE=base RELEASE_VERSION=7
    - OS=centos IMAGE=build RELEASE_VERSION=7
    - OS=rhel IMAGE=base RELEASE_VERSION=7
    - OS=rhel IMAGE=build RELEASE_VERSION=7
    - OS=alpine IMAGE=base RELEASE_VERSION=3.6
    - OS=alpine IMAGE=build RELEASE_VERSION=3.6
    - OS=alpine IMAGE=base RELEASE_VERSION=3.7
    - OS=alpine IMAGE=build RELEASE_VERSION=3.7

  global:
  # Docker User
  - secure: rgZAzwn/1S/CGjIqm30Xno+BxkhFSXsewo88VwjFKoVulOSOKnsDGpecQHX2A3io2GpqVg3MVQ8GuD1EoSgFOjScHkui5LRg8J19t7J0zq3rjtsVu8ylNIdnSbEm/F0ISZmyTIP92bwFCgxEHvfEyghcl2DNCb8yRt4hGcqhgpj950dTkpbopfMv/5fgCRQRa4/xIkHKCuavt9L8mIgnT2HHXhscP0f4Od5kCjUSccrnP3PiLozAdP8FWyx3ulo7j1/yWluRN3V7vdJHD2w/5DKF57JqJlCC0oOOVedaNFKZNQN5gpx4m4QbqiJ3MB07aOeCajJ5I8h9wrVPo3Msw0uZTrOGdYVNElqZ2fddSIgoMmLwTXRGajdDv28DnGCU5eStqzj+wr1NFk/apVFa7os40LZdu5vMeRPiTdkLttmyMJS3B111v0aFxkx/nOUIwfgZ4n7lAL0du/hYkD5r6tKnBVcwgl3CZLxfDuv/B9vbZIi2fQzrVwJU9WNUfDYUmwaPZ5lr1qt94N7CMJroQcsiRsKDCnLpTUUJ/LScHK3V7yO1KMweK/iPDy3GxK1oajLiS0fmHc0vPIjgRWPZclloq2bQu+4Jf9xUFYUlzTwzT7xOBaChoZECgTEERsp1CQ36eawGdpIYYv3gISaZfjPgRyj/T7C56oYarhLMLa8=
  # Docker Pass
  - secure: kErN20saYg93IlEfmBcJH8aBsDz4eYtXDknvIULmmlbABRXYOD8UwfR6rJXL8yui//0AUU6tQCZ+4hqiuXOGQxS77+36nN9l7ph2OF+gHkBadB2ZFGy+KiVh/s6aWihDAETjvfT3dkr7LMlcvbEow+t7HCweqoPbga7N+qAEGUHz3flnUl7q7gX6HgOhhsLjDCFJLWEqbAXxXUzTHArHW0sTRBd6YcXxEipTArfkpucpMzE/lZhNEjExDyTPpQE5vzrbabLMAjNfJvhe6ms/RX3Eynha/Sd0Q4v2vid989sY3nyfLMxyN4GRcnpqquI16FAMfJCVd+q7SyoLScZJVpuWQ1lKGe9bQzbS9FDLLUw2JgDFJADJ4ALuomkfqaC4zRZ1OryZ4RGGOOyMT+qf27tkOqRjezSZGAEVXomJgRrOzvyy4wO8pYG8Tdj43/GnMq27yh53NWEhMwXwjgnKd2Rr4Ui5RSDNhInDbNEBS7u/tAfzDzf0vaaTym2Sz3Fqra5XPoOK4Nvg3sWbCC37l2ZyrI5Eigl+Ih3/7QPkUFa+CCwh1bHdESZAsf1h807lxy/YfG6WE9NU2LitBL9WdScZtfpQhr93fFEaIgFJ/d4+Re4xZCEshIG/D69yfXFYFVlGiDjIdfcPBWsoIml52sZxRqc1nzHVYnPVIoKHZ/o=
  # RedHat Username
  - secure: jWXwOV/n3kypmkN6nM7sgU7hpWl0tiUlwB4/eMM5yYd3c0ByTpatfTWCFZxzo0h5ccgM/ce5Bx5LTMzA3rttV0ri9hfphrrO6mhJf1y5GwsBNoHFWk9cWSaHk13iL56mi1JI+LJA/T3q4jacOJ9DCQqzYKE+MV/RpY8iTBgeUif+P6dVCFpmKbEOVaChI9y/EV6lj4gL/0U8Fj7khLl8VVsvvGhngbVoZb4Wd1jnOklrI1z5oKYImXaFIbwhlbqvQqnca9TnewBAQILwCTQzrnXd+2dsnpSyq95RpdozUKOul3ImYnNfcWkFloudbVDEFJpldSSjWpV1gqVTo/cGwhOuNIdAwqlDZVFHI0YG+uNXVwP1fPIdVu56LDsAitIx55oua3xOTeqBm1hnOkF09iSnEKCG8Xkfr34I2rzsxq5hB7w5xT4HRPZ5ynIlbtUMN70UBrXHMuoYV5EAblRVYJ6C5koeGXZjOvmQ/ItHi3OvhL0puJhjP9rTfhXSeXdFQwZ2U2tfEV49/64AJ+AY/CY5A9Z7vQFqD2JcctK5lNjlORoKv8ThIkWTiq/9MSSKb+MEB3WFis9+Ux1/ViZxLY6M6EFStWooUCPP0qkMzdxnK658vflbFmLgR+kNa+IIkVqbJQyyBZAvYAInyKCH1XOjB8XYOhLHBmeShWdhAFA=
  # RedHat Password
  - secure: VpIb5L8GjhjpUA62E0imIFdLJ66I/ATfhTPAHa0Shz+BjDMcNzHoeqIEOfBw0hQ9/+7NLsM/yNV3yWp5ZT/g8sHkJhRIhQ+/xi0VXIOO7fgwQYY0lMdYG+XePwRLjxWQhdRWtLKZ8ssvSBQJx28ahzLrgYhXqQhqlGVZT9DXqgVq4XrPcbbikaYzU1GKXOxijgcoenQa1/plZ7+fIciikWlWA6JW8ttsoo3z5dxdfp0/V3ncJn9nbcYFvMHwqtWXIb19BtrxbR23YBxaa8IbnxYI5lu18x8hSiSYkmYERVo1AJuErkcsoD/hsPwqhbYRizIhwrowHl8Gl5JltQKLTJ5w4YUDBK0lm7OUNS0fCf8IG8je05uwuRopMwOANAlZCdqFfa+AKLrnpQ7+6ecj/PTOc/luDn51TzLdI2Ny7caIVf/aSMVp5RxHVzo7gE/9Er+f2HnUuDtlxWLURXX2FwD5NXm8IHSozfnAcxgNwKh5RurwcCfQOA5Et62OMW65k9O+cRoBv5tqsNhzWB6ZHVoFRplQTIaWzpIVWFPQM1jLAGJMMzOaazmxQAcWfeuPMOmZsRKvmigfTg4MsOnMEgB/0Cdi1NR0Ia2LIQjQ/n9kA/dtFkErZ55fcQafRJ6rTgx+FFRtvVRURgjufJSMfvHi+Gkn90sZRvuBHYCIA8s=
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce -y -qq
  - echo "DOCKER_OPTS=--experimental=true " | sudo tee --append /etc/default/docker
  - sudo service docker restart

before_script:
  - docker version
  - export IMAGE_NAME="charlesportwoodii/$OS:$RELEASE_VERSION-$IMAGE"
  - echo $IMAGE_NAME
  - echo $DOCKER_USER
  - echo "export REDHAT_USER=$REDHAT_USER" > .secrets
  - echo "export REDHAT_PASS=$REDHAT_PASS" >> .secrets
 
after_script:
  - rm .secrets

script:
  - docker build -f $OS/$RELEASE_VERSION/Dockerfile.$IMAGE -t $IMAGE_NAME --compress --squash .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $IMAGE_NAME
