sudo: required

language: bash

services:
  - docker

env:
  matrix:
    - IMAGE=trusty
    - IMAGE=xenial
    - IMAGE=centos7
    - IMAGE=rhel7

  global:
  # Docker Email
  - secure: hTz5hqFgOwlUy8TrvxNjZQThhdj0D5AVBWLCE6NjvMx6fNEVgOqt0Pfsaa4z/t0sqst83+yJLvFGZZiVA5xA5WB4mLvR7oZ/DXOyj602/aiim9hLlLX8NMLbXUSVyMuY5IPwQFGgJqf4eUVScMfJqKy2WRCTqg8Rv6BvXkQwMU+zUN76zMlKY1wWbBE2uGUeyCwdyrTFzsUggxiR6mzQtROMx+ryAcwnktg6Fg1N5xQJkuhp208+dyHpey7eVZnio07snCPuOXHmR9micia+oW77pHx4V0P77tpC3nzfBwvVHthSNt4STGlS+Q+kBQtf9Fc8F0YWV6bgV5LItO4X35b3u2Z4g1Z7t7371/JSo6p96zHtaLvxGx7u5UoPdH7am/+kTJcfLVHpyJsN7wt2NAgmFL5Qn+6OQngm8g2pAbWyLHkSKjcsBGGDr6Oa3F+RmDblsNv1Ls1r6Z1E25dg5wtna0dtWrrM5PLnZ76M+gb3h17ObwoXhdBjXKk2CxkDZtMWd46pO5vgq7wWY8RPq9mvISJNKh2U94smfo3Kj/Ow5dpNMqAXJAnMIqXtTe/yntc/cPvEhrZFB1pnolSsa1/6aOKqFGPYzm13y63UFSOLY/GtxJbjaEpnybo+8tWAN1B5s88Wot8AOT2izSNK5alKl/FAP/M8XQkt9f2bbo8=
  # Docker Username
  - secure: eEsFsnGv15GJWs05bh0db+RoBL8q79bsuJpke5Z0lGk69m8Pa/zpLHFO4V+wvZq05plHiL2w43cnTgFNEjEuN2LVhgwO6WDC/RCv1b3ayRkbEkz1yBsme1yafrjmNXrcMNvKu0YbOU8efVP76AxJKLjlfnwxfzZVbvhTGmroiDHDlVLLsE1H/QJ9pEnlc4vzxy6VIpdB+YZ3v2bFQOTKWzgxzmubSijA2OOAasotU9MHn8TUi96QHUuYTqv/4J3S4HRpAoKcYBS4cF5Q1Aqmz62yLf7MQoKkYfdbZ4tuEc/Ft5Bx4WXK4TklPuYwB53JRwBWdInH+yJp4RlHWA4792vTr9YgveZPiVo0SNMRoaDhgAw+7VIPJ6+74r2QLNqlk40+/t5w1FIFS1Nln1EomG/jUQpF07aQVvRQr5q/jWeBDinf0oPLj0nzLTe0B7KGdjGhMFBR4vNkkHFfB4ylMEprARDhY6JJSAF/LqMGYXBklGD+lcvumOGATe64hYl47iwDC6oD3sCS2f/qBxj1c0QSmNgSjGeOPv+wyeH4zoKbKkQYbCs6rYYE+m+oYtDO8KAAIukoYyX5Ewi9H4Dk31bViHM3Yhn/MJFzrAjS1hsVUsV+3pi0hzE9ArRk5HAECma5suxd+7hS252mxZiCCxQakSmicx6RxjS0dCz1/vY=
  # Docker Pass
  - secure: "hFvkk0Oo3jN4Ijj/qiS3mcTVNOj6msMQqtsQnhekjtEGY4DGfmz3no23Zr/GAXr8MOZCpk6bj0R8JcdLJJTsUziyyujtchm7knm1B5naevaX82UG/DVGkH0lKwYOkM3ff+FOL5FnNV2+onf1OUQvARSaneGTmlTtoHBrejYIVlfyY8Mvd60AJNW6UWOEKxCP8Xz8XUs50fVElWIvYslDTJI6r/9n83jXM5Eva6/gOlW7LZjvCXTORQeOXv8VL8ppuBljxsLQ5dRSJw/8EhNDwcftAknFE+7dS7W3qPoto416mY0iPO/ZxacXTDJgaYAjI+pA2W5V0JPH/oQGR6hWh+Miw4zSrMOEdeBIREei9shVsytigVDxHh2wBdO/TozI+AUBxNhUOEZhV8aTbloxpQ9qPbySuaNY29ynOyi30saz94sWz/5+tSLvt7aAHKLgNU+12PD2ZnLyD5XWfM8KtN26upSFkq2xQLMyy1KKAEdjk951DkO5WMJiJHTTcEpN+Reqy4a2V8jIFxkaEs6yashNGbRciYaMjTW5xC7n74rbE93/Q9zxvgiwZEAu+T6p3NWKyg0//RmlEjTN9pwsufFhfG1+0Tblo/1wjlv++51RktPtk8SQTce1lcSwWW28Ar5mnUSm4HlHMprEPZP8mY+mKx2stN6q6i/+W0b1o6A="
  # RedHat Username
  - secure: fv8OyCmaMI+VQdazotTDPC8wVBMYv/2oZzpRW6GZ0afT24xG0OML/TUVuYJglgHxyRtQDSlkSkaEg6j39sFUAU/5Aln1C7rN/+AOJsabKNqx7mKIXORFHFSrAdSVegkEyuUfCCef0QVPyLu3jTudwDcvVNG0btB+Dr+nz3tAEK3p/ZkBs7hnIJ5KvEUFGK5GY+hU8MN24E0IArZwOl2HN8iEI+EU+/N/1YPS1ibNdAXlf+u7vBngU6ovPkV+KIRCaNnZ7+sFMw+Er6hzSyLrwzJ5uSnttjMqjw13I+E0HuEteGY3oPQwuTIOspPBWLuSPpWoAZBdvZocpy5MY0UoHjenz9Eyj59vQyiXa/pxx8MnRROhekfxZQGAjQntnAIj1X17h9WRV4+V01KDMo4DHO0zJ4GlyqX7ftfpchts1eLUTsH5UX/OGx9IdG/bcdQg4BOLeMc2Hsx0wJruz14qxTFrEoLVBRMFdMEMj1T9Ql7vD71ax0dKgXJZH6UqNXlIndauPKCv+jYfHwsWEXNj+gRXBz63v3ImbTgroPNFHMwp87KziQqVRxf2MHLx6pQnW3faapZyBi9+N89zCj9kY66kCsvnxzwYcv0j1hjvnbbBUUCTZknUgWntE2seBrET3ViqjoJ65Tmq//n+yT6Xv7HctmxBJEpfKwXvaGrPVR4=
  # RedHat Pass
  - secure: kdt5lLdCTyobHT6T2a9UXbT92pYPv0moWuCrY3/CHTokDGWKFhs/ioYURpxIBf3Ge9fNzq8wIlxA2G0uHpkKIaxjn0Kjh+CbMD73ykPIzozS0USBMb2zDCMBOkzJlI70WCY+wVXzarqpIacTersL4wyahy3Pf17WWEmXKdIeSxpObLMurmPiHgKA4HmnkMW6EoNJHUKqpw+kltg9SmixJZlu2fgiGvf1lJCgO0phwGQHvKyN9PcSvPQKm67Zz0Im2PGsZLSRK7+5/dpO3PdpKhZa3MO8eBE0NiCwaKCsiin9M+g6/bXQPJqenN07xBOIqMDYIVlHdlTQU4WHItGWiOvESGqErSqW6tXSxQGEyS9drTKOc0jJW7VBNvKIyjSsroh9vV7aDjypEEL1MuPyiU+B6jLNYEOPafnJVCnCBxSVoq0i5rEr6NgTdhYZWNGPv6/tn/o5VpKjgcXZQMec766VBz54BSm9O7hdD5h1/A7jU5bpr9ak+8yb/VPmIFj1CO7Q5ChSzV1MKyPey59yANQpn6JnbT83/HAvib3+t5+UotaEkwkeclnPYEBzDYb6ogX9uOuvsZOWQmsYBAQI0of4qAABPHdjbpR6x40/qMpHq892x5s6LRywUf3wtn3uOtZE2YL1oCfmyd46+sB9ZxofVV6lGU0WoibgmHSs2gY=
  - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - export REPO=charlesportwoodii/docker-images
  - export TAG=$IMAGE

script:
  - docker build -f $IMAGE/Dockerfile -t $REPO:$COMMIT . --build-arg REDHAT_USER=$REDHAT_HSER --build-arg REDHAT_PASS=$REDHAT_PASS
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$IMAGE-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
