dist: trusty
sudo: required
language: generic

matrix:
  fast_finish: true

env:
  matrix:
    - OS=ubuntu IMAGE=base RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=14.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=16.04
    - OS=ubuntu IMAGE=base RELEASE_VERSION=18.04
    - OS=ubuntu IMAGE=build RELEASE_VERSION=18.04
    - OS=centos IMAGE=base RELEASE_VERSION=7
    - OS=centos IMAGE=build RELEASE_VERSION=7
    - OS=rhel IMAGE=base RELEASE_VERSION=7
    - OS=rhel IMAGE=build RELEASE_VERSION=7
    - OS=alpine IMAGE=base RELEASE_VERSION=3.6
    - OS=alpine IMAGE=build RELEASE_VERSION=3.6
    - OS=alpine IMAGE=base RELEASE_VERSION=3.7
    - OS=alpine IMAGE=build RELEASE_VERSION=3.7
    - OS=alpine IMAGE=base RELEASE_VERSION=3.8
    - OS=alpine IMAGE=build RELEASE_VERSION=3.8

  global:
  # Docker Email
  - secure: hTz5hqFgOwlUy8TrvxNjZQThhdj0D5AVBWLCE6NjvMx6fNEVgOqt0Pfsaa4z/t0sqst83+yJLvFGZZiVA5xA5WB4mLvR7oZ/DXOyj602/aiim9hLlLX8NMLbXUSVyMuY5IPwQFGgJqf4eUVScMfJqKy2WRCTqg8Rv6BvXkQwMU+zUN76zMlKY1wWbBE2uGUeyCwdyrTFzsUggxiR6mzQtROMx+ryAcwnktg6Fg1N5xQJkuhp208+dyHpey7eVZnio07snCPuOXHmR9micia+oW77pHx4V0P77tpC3nzfBwvVHthSNt4STGlS+Q+kBQtf9Fc8F0YWV6bgV5LItO4X35b3u2Z4g1Z7t7371/JSo6p96zHtaLvxGx7u5UoPdH7am/+kTJcfLVHpyJsN7wt2NAgmFL5Qn+6OQngm8g2pAbWyLHkSKjcsBGGDr6Oa3F+RmDblsNv1Ls1r6Z1E25dg5wtna0dtWrrM5PLnZ76M+gb3h17ObwoXhdBjXKk2CxkDZtMWd46pO5vgq7wWY8RPq9mvISJNKh2U94smfo3Kj/Ow5dpNMqAXJAnMIqXtTe/yntc/cPvEhrZFB1pnolSsa1/6aOKqFGPYzm13y63UFSOLY/GtxJbjaEpnybo+8tWAN1B5s88Wot8AOT2izSNK5alKl/FAP/M8XQkt9f2bbo8=
  # Docker Username
  - secure: eEsFsnGv15GJWs05bh0db+RoBL8q79bsuJpke5Z0lGk69m8Pa/zpLHFO4V+wvZq05plHiL2w43cnTgFNEjEuN2LVhgwO6WDC/RCv1b3ayRkbEkz1yBsme1yafrjmNXrcMNvKu0YbOU8efVP76AxJKLjlfnwxfzZVbvhTGmroiDHDlVLLsE1H/QJ9pEnlc4vzxy6VIpdB+YZ3v2bFQOTKWzgxzmubSijA2OOAasotU9MHn8TUi96QHUuYTqv/4J3S4HRpAoKcYBS4cF5Q1Aqmz62yLf7MQoKkYfdbZ4tuEc/Ft5Bx4WXK4TklPuYwB53JRwBWdInH+yJp4RlHWA4792vTr9YgveZPiVo0SNMRoaDhgAw+7VIPJ6+74r2QLNqlk40+/t5w1FIFS1Nln1EomG/jUQpF07aQVvRQr5q/jWeBDinf0oPLj0nzLTe0B7KGdjGhMFBR4vNkkHFfB4ylMEprARDhY6JJSAF/LqMGYXBklGD+lcvumOGATe64hYl47iwDC6oD3sCS2f/qBxj1c0QSmNgSjGeOPv+wyeH4zoKbKkQYbCs6rYYE+m+oYtDO8KAAIukoYyX5Ewi9H4Dk31bViHM3Yhn/MJFzrAjS1hsVUsV+3pi0hzE9ArRk5HAECma5suxd+7hS252mxZiCCxQakSmicx6RxjS0dCz1/vY=
  # Docker Pass
  - secure: "hFvkk0Oo3jN4Ijj/qiS3mcTVNOj6msMQqtsQnhekjtEGY4DGfmz3no23Zr/GAXr8MOZCpk6bj0R8JcdLJJTsUziyyujtchm7knm1B5naevaX82UG/DVGkH0lKwYOkM3ff+FOL5FnNV2+onf1OUQvARSaneGTmlTtoHBrejYIVlfyY8Mvd60AJNW6UWOEKxCP8Xz8XUs50fVElWIvYslDTJI6r/9n83jXM5Eva6/gOlW7LZjvCXTORQeOXv8VL8ppuBljxsLQ5dRSJw/8EhNDwcftAknFE+7dS7W3qPoto416mY0iPO/ZxacXTDJgaYAjI+pA2W5V0JPH/oQGR6hWh+Miw4zSrMOEdeBIREei9shVsytigVDxHh2wBdO/TozI+AUBxNhUOEZhV8aTbloxpQ9qPbySuaNY29ynOyi30saz94sWz/5+tSLvt7aAHKLgNU+12PD2ZnLyD5XWfM8KtN26upSFkq2xQLMyy1KKAEdjk951DkO5WMJiJHTTcEpN+Reqy4a2V8jIFxkaEs6yashNGbRciYaMjTW5xC7n74rbE93/Q9zxvgiwZEAu+T6p3NWKyg0//RmlEjTN9pwsufFhfG1+0Tblo/1wjlv++51RktPtk8SQTce1lcSwWW28Ar5mnUSm4HlHMprEPZP8mY+mKx2stN6q6i/+W0b1o6A="
  # RedHat Username
  - secure: "FqcCLYIqLSDLqH0jtz5rubed5jRXtLLxrBru/9aXmezFpnLyus2HkvgUh85j4x8gQJ/dpgZpZ9k5/Poqw0Uwe/dcxj3kl522UHMnm2nsxXfGMxem70hFoepUmmzWBaeX7nNFx7oQMMv6uP7ude25G19TFPP8+VSWIhMXDdJoYVCp7ezu1dtDialpdcqRw7d/HbHwCmLzTpljHjNHeRCnYD7XGVSlK349PZEfzouOiu8rWvu1BlJHhRPZOrBzTbvtVJvV9LgA0emT0eOKfWgyS7pykHJ7SUK1zD9fuFF5Kjz4m0nzzumD2ogC9HD8JvD9D7gzHrJ+d8h2uYECDzAPJoVr663LImsxnBz/WfUqAruhScqq8U4Rgu+5a1eMK/Y7xz1mx+7r98SFWDhyKo08W5tNz+EunPm5dPVmj5V58tIb2crD7IBuvDfW+6NYZhGidMIrfSqnvsOft48OdFI85BmAmlJwc/bGqLa5AGKNqD3/y3qSFqdBhGSul7WLyB8P/rWXxYOx9wXLd/FKhOhsdjsd2wHZLq3V40bOCNBsU+k4+op7FpU7WP+RDufvEI1I1X3hoXVlCPGb/1vPUK8uuRntI3g/0uEB8GoGIwhf8i5HzIvWUwdtmoIjwmQEUu3Qvbt88CymDZvUDkke210TXUYBVNFZEupPnppRHqFciBA="
  # RedHat Password
  - secure: "aQevB1xHXsUE53hhR9PDqeNXN+ICnjSnXM5PjqkMqTOlIzST6IxJcfesqGyTIRbgkYnZ3wsY2ZuiJI7VhaeDO1Kr4LosGQVRAG+yu7WIT6otW1EmFJfO/5+IPfTY6I+Abs+dal7Txg4uzKXLlRPLvEp3oJLUL1FIE5TzCLhc/snsL/epOSTidvFnwfLF7NfxiyqY5MoRIM28LPg8QHzohvCHAR/SiZuwJonWzEz3StZU/gOD+bR5WRarIfGRaYiMuC9fwQQqS6DrnX4WCzJkE5A71I+HTzCQW/hEqZSVCJF7sFqJrIrRPHk2gmpbDEcW9xdZ/707DrBqS5QmfqF7149Kp2TXt29gs3CZo8EYzqKP7r3DtP1a/1NelKk9fxyRD+5ts8V8Gvj5cpiRO0Y23KudheDAlybzT1WOJihkQNJ48rGT5o0TGq2U+2oj6XOInAuz4HH/j/QUkJLNsqgFtcjRgKmxY634Q6EmuQBUAFlUVP32H7EaM6jeFj4NLeiPSAB/QkyQovjdQd+d6x93Z8IqMuuPY4jyXcDrcjYfg5ky7V4AUV3Us9yxUuFYlAG/DMnxs5l70k17P+JDFzzWg4uJpvtkM1SVssVxH9qbFUyH+4G3NsNm3bX8bn15ZnxsKj0oVW1CuZoqsAfELjxgfOX+F1cC5vp3qW3bXvvJJBo="

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce -y -qq
  - echo "DOCKER_OPTS=--experimental=true " | sudo tee --append /etc/default/docker
  - sudo service docker restart

before_script:
  - docker version
  - export IMAGE_NAME="charlesportwoodii/$OS:$RELEASE_VERSION-$IMAGE"
  - echo $IMAGE_NAME
  - echo "export REDHAT_USER=$REDHAT_USER" > .secrets
  - echo "export REDHAT_PASS=$REDHAT_PASS" >> .secrets

after_script:
  - rm .secrets

script:
  - docker build -f $OS/$RELEASE_VERSION/Dockerfile.$IMAGE -t $IMAGE_NAME --compress --squash .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $IMAGE_NAME
