FROM alpine:3.7
LABEL maintainer="Charles R. Portwood II <charlesportwoodii@erianna.com>"

RUN apk add curl wget --no-cache && \
    curl -qs https://gist.githubusercontent.com/charlesportwoodii/2253f1e82b60c7334b78a012c2d2beea/raw/477a43a4ad16b2f3b83790e45131390f943f0691/charlesportwoodii@erianna.com-59ea3c02.rsa.pub -o /etc/apk/keys/charlesportwoodii@erianna.com-59ea3c02.rsa.pub && \
    sh -c 'echo "https://apk.erianna.com/v3.7/main" | tee -a /etc/apk/repositories' && \
    apk update && \
    rm -rf /var/cache/apk/*
    